import * as THREE from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
import {Neighborhood,plots,plot,distance} from './model.mjs';
const $=id=>document.getElementById(id),model=new Neighborhood();let selected=null,mode='select',measure=[],toastTimer;
const name=o=>o.id.replace('house-','H').replace('garden-','G'),isHouse=o=>o.id.startsWith('house-');
const scene=new THREE.Scene();scene.background=new THREE.Color('#dceefa');
const renderer=new THREE.WebGLRenderer({canvas:$('scene'),antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;
const camera=new THREE.PerspectiveCamera(40,innerWidth/innerHeight,.1,600);camera.position.set(86,100,102);
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,0,0);controls.enableDamping=true;controls.minDistance=45;controls.maxDistance=240;controls.maxPolarAngle=Math.PI/2-.08;
scene.add(new THREE.HemisphereLight(0xf4fbff,0x9eafa1,2));const light=new THREE.DirectionalLight(0xfff3dd,2.5);light.position.set(-30,70,30);light.castShadow=true;light.shadow.mapSize.set(2048,2048);Object.assign(light.shadow.camera,{left:-65,right:65,top:65,bottom:-65,near:1,far:180});light.shadow.bias=-.001;scene.add(light);
scene.fog=new THREE.Fog(0xdceefa,210,450);
const ground=new THREE.Mesh(new THREE.BoxGeometry(64,1,64),new THREE.MeshStandardMaterial({color:0x9ab9c2,roughness:.9}));ground.position.y=-1;ground.receiveShadow=true;scene.add(ground);
const world=p=>new THREE.Vector3((p.x-2.5)*10,0,(p.y-2.5)*10),tiles=new Map();
for(const p of plots){const mesh=new THREE.Mesh(new THREE.BoxGeometry(9.7,.5,9.7),new THREE.MeshStandardMaterial({color:0xa7cbb8,roughness:.85}));mesh.position.copy(world(p));mesh.position.y=-.25;mesh.receiveShadow=true;mesh.userData.plotId=p.id;scene.add(mesh);tiles.set(p.id,mesh)}
const objects=new THREE.Group(),measures=new THREE.Group();scene.add(objects,measures);let labelPoints=[];
function clear(group){for(const o of [...group.children]){group.remove(o);o.traverse(n=>{n.geometry?.dispose();if(Array.isArray(n.material))n.material.forEach(m=>m.dispose());else n.material?.dispose()})}}
function notify(s){$('toast').textContent=s;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,3300)}
function setMode(m){mode=m;if(m!=='measure')measure=[];document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));$('hint').textContent=({select:'Pick a plot to explore',house:'Pick an empty plot for a new home',garden:'Pick an empty plot to plant a garden',move:'Pick an empty plot to move your selection',measure:'Pick the first plot to measure'})[m];updateMeasurement()}
function updateMeasurement(){clear(measures);$('measureLabel').hidden=measure.length!==2;if(measure.length===2){const a=world(plot(measure[0])),b=world(plot(measure[1]));a.y=b.y=.7;const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints([a,b]),new THREE.LineBasicMaterial({color:0xe7f0ff,depthTest:false}));line.renderOrder=10;measures.add(line);for(const p of [a,b]){const marker=new THREE.Mesh(new THREE.SphereGeometry(.65,12,12),new THREE.MeshBasicMaterial({color:0xffffff,depthTest:false}));marker.position.copy(p);measures.add(marker)}$('measureLabel').textContent=`${distance(plot(measure[0]),plot(measure[1])).toFixed(1)} m`}}
function refresh(){const snap=model.snapshot();$('coverage').textContent=snap.coverage===null?'—':`${Math.round(snap.coverage*100)}%`;$('bar').style.width=`${(snap.coverage??0)*100}%`;$('ratio').textContent=`${snap.houses.filter(h=>h.servedBy.length).length} / ${snap.houses.length} homes`;$('houses').textContent=model.houses.length;$('gardens').textContent=model.gardens.length;$('empty').textContent=36-model.objects().length;
 const o=model.occupant(selected),p=plot(selected),neighbors=o&&isHouse(o)?model.gardensFor(o):[];
 $('move').disabled=$('delete').disabled=!o;
 for(const [id,tile] of tiles){tile.material.color.set(id===selected?0xffeab2:neighbors.some(g=>g.plotId===id)?0x86daa1:0xa7cbb8);tile.material.emissive.set(id===selected?0x503b11:0)}
 clear(objects);$('labels').replaceChildren();labelPoints=[];
 for(const obj of model.objects()){const house=isHouse(obj),served=house&&model.gardensFor(obj).length;const h=house?obj.height:1;const mesh=new THREE.Mesh(new THREE.BoxGeometry(house?6:8,h,house?6:8),new THREE.MeshStandardMaterial({color:house?(served?0x519ff3:0xf7a061):0x55c783,roughness:.65}));mesh.position.copy(world(plot(obj.plotId)));mesh.position.y=h/2;mesh.castShadow=true;mesh.receiveShadow=true;mesh.userData.plotId=obj.plotId;objects.add(mesh);const outline=new THREE.LineSegments(new THREE.EdgesGeometry(mesh.geometry),new THREE.LineBasicMaterial({color:house?0xc6e1ff:0xb4f0cb,transparent:true,opacity:.3}));mesh.add(outline);const el=document.createElement('div');el.className='object-label';el.textContent=name(obj);$('labels').append(el);const point=mesh.position.clone();point.y=h+1.5;labelPoints.push({el,point})}
 if(p){let html=`<h2>${o?name(o):'Empty plot'}</h2><div class="row"><span>Coordinates</span><b>(${p.x}, ${p.y})</b></div><div class="row"><span>Type</span><b>${o?(isHouse(o)?'House':'Garden'):'Empty plot'}</b></div>`;if(o&&isHouse(o)){html+=`<div class="row"><span>Height</span><b>${o.height} m</b></div><div class="status ${neighbors.length?'':'no'}">${neighbors.length?'Served by a garden':'No garden next door'}</div><p>Neighboring gardens: ${neighbors.length?neighbors.map(name).join(', '):'None'}</p>`}else if(o){const hs=model.houses.filter(h=>model.gardensFor(h).some(g=>g.id===o.id));html+=`<p>Serves: ${hs.length?hs.map(name).join(', '):'None'}</p>`}$('detail').innerHTML=html}else $('detail').innerHTML='<h2>Hello, neighbor!</h2><p>Pick a plot to see what’s growing nearby.</p>';updateMeasurement()}
function act(id){try{if(mode==='house'||mode==='garden'){model.add(mode,id);selected=id;refresh();return}if(mode==='move'){const o=model.occupant(selected);if(!o)throw Error('Select a house or garden first.');const changed=model.move(o.id,id);selected=id;setMode('select');refresh();notify(changed?'Moved! Garden coverage is up to date.':'Already home — no change.');return}if(mode==='measure'){if(measure.length===2)measure=[];if(measure[0]===id){notify('Pick two different plots.');return}measure.push(id);$('hint').textContent=measure.length===1?'Now pick a second plot':'Measured! Pick a plot to measure again';updateMeasurement();return}selected=id;refresh()}catch(e){notify(e.message)}}
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();let down=null,hovered=null;
renderer.domElement.addEventListener('pointermove',e=>{pointer.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects([...tiles.values(),...objects.children],false)[0];if(hovered&&hovered!==selected)tiles.get(hovered).material.emissive.set(0);hovered=hit?.object.userData.plotId??null;if(hovered&&hovered!==selected)tiles.get(hovered).material.emissive.set(0x16291c);renderer.domElement.style.cursor=hit?'pointer':'grab'});
renderer.domElement.addEventListener('pointerdown',e=>{if(e.button===0)down={x:e.clientX,y:e.clientY}});
renderer.domElement.addEventListener('pointerup',e=>{if(e.button!==0||!down)return;const delta=Math.hypot(e.clientX-down.x,e.clientY-down.y);down=null;if(delta>5)return;const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects([...tiles.values(),...objects.children],false)[0];if(hit)act(hit.object.userData.plotId)});
document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));
$('delete').addEventListener('click',()=>{const o=model.occupant(selected);if(o){model.remove(o.id);setMode('select');refresh();notify('Removed. Garden coverage is up to date.')}});
$('reset').addEventListener('click',()=>{model.reset();selected=null;measure=[];setMode('select');refresh();notify('Back to our little starting neighborhood.')});
window.addEventListener('keydown',e=>{if(e.key==='Escape'){measure=[];setMode('select');refresh()}});
function resize(){renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}window.addEventListener('resize',resize);resize();refresh();
function screen(point){return point.clone().project(camera)}
renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera);for(const {el,point} of labelPoints){const v=screen(point);el.style.left=`${(v.x+1)/2*innerWidth}px`;el.style.top=`${(-v.y+1)/2*innerHeight}px`;el.style.display=v.z>1?'none':''}if(measure.length===2){const a=world(plot(measure[0])),b=world(plot(measure[1]));const v=screen(a.add(b).multiplyScalar(.5).setY(2));$('measureLabel').style.left=`${(v.x+1)/2*innerWidth}px`;$('measureLabel').style.top=`${(-v.y+1)/2*innerHeight}px`}});
if(document.modelContext?.registerTool){const lifecycle=new AbortController();const register=tool=>{try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}};register({name:'read_neighborhood',description:'Read the current plots, objects and garden coverage.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>model.snapshot()});register({name:'edit_neighborhood',description:'Add, move or delete one object, or restore the example. Updates the visible grid and coverage.',inputSchema:{type:'object',properties:{action:{enum:['add_house','add_garden','move','delete','reset']},plotId:{type:'string'},objectId:{type:'string'}},required:['action'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||typeof input!=='object')throw Error('Invalid input');if(input.action==='add_house'||input.action==='add_garden')model.add(input.action==='add_house'?'house':'garden',input.plotId);else if(input.action==='move')model.move(input.objectId,input.plotId);else if(input.action==='delete')model.remove(input.objectId);else if(input.action==='reset')model.reset();else throw Error('Invalid action');selected=null;measure=[];setMode('select');refresh();return model.snapshot()}});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true})}
